export const GET_PERSONALBOARDS_REQUEST = "GET_PERSONALBOARDS_REQUEST";
export const GET_PERSONALBOARDS_SUCCESS = "GET_PERSONALBOARDS_SUCCESS";
export const GET_PERSONALBOARDS_FAILURE = "GET_PERSONALBOARDS_FAILURE";

